---
name: Pull request build

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  task-check:
    name: Check task completion
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  conventional-commits:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    name: Lint and test project
    strategy:
      matrix:
        node: ['18', 'latest']
    env:
      MAIN_NODE_VER: '18'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: get Python location
        id: python-location
        run: |
          echo "python-bin-location=$(echo $pythonLocation)/bin" >> $GITHUB_OUTPUT

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.1'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Install project modules
        run: npm ci

      - name: Lint source files
        run: npm run lint

      - name: Run unit tests
        env:
          EXHORT_PYTHON3_PATH: "${{steps.python-location.outputs.python-bin-location}}/python3"
          EXHORT_PIP3_PATH: "${{steps.python-location.outputs.python-bin-location}}/pip3"
        run: npm run test

      - name: Compile project
        run: npm run compile

      - name: Run integration tests
        run: npm run integration-tests

      - name: Run integration tests cli
        working-directory: integration
        run: bash ./run_its.sh

      - name: Upload coverage reports
        if: ${{ matrix.node == env.MAIN_NODE_VER }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage/coverage-final.json
